baseURL = "http://example.org/"
languageCode = "en-us"
title = "Russell Osborne"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/rposborne\" target=\"_blank\">Twitter</a> | <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> â™¥"
disqusShortname = "rposborne"
publishDir = "docs"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Place labels here."
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Russell Osborne"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/rposborne"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/rposborne"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/rposborne"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/rposborne"
fa_icon = "fa-linkedin-square"
